name: KyoEconomy
version: '${project.version}'
main: org.kyonami.kyoeconomy.KyoEconomy
api-version: '1.20'
description:  KyoEconomy Plugin

commands:
  money:
    description: "KyoEconomy"
    aliases: [economy, eco]